---
title: "Unit 7"
output: ioslides_presentation
---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```





## Unit 7

Continuing Survey Design And Introducing Interviewing Methods


## Overview Of Surveys In Program Evaluation

In the last unit we covered many of the important principals of survey design. In this unit we will continue to discuss survey design. In this unit we will discuss some more detailed aspects of creating individual questions and also how to create an entire survey that consists of the appropriate questions. We will also take many of these principles and begin discussing interviewing methods.


## Details Of Survey Question Design

Last unit we left off with the discussion of how the design of a question could lead respondents to likely answer in a particular way. This will add bias and not be ethical. As we continue this theme, objectivity is very important in research design. We can now discuss some of the detail of how questions could be leading.


## How To Ovoid Leading Questions

One type of leading question is when the question provides information that would lead to a particular answer. Continuing with the pay raise and productivity example we can see how you could create a leading question. An example question could be: "Past research has shown pay raises can result in higher productivity. Do you feel that you are more productive with your pay raise?". This is a leading question because it reveals that research already supports the increase in productivity. Because the question tells the respondent that it is already "true" or supported, the respondent may feel like the only correct answer is to say that the pay raise has led to more productivity for the respondent. This is a form of bias.


## How To Ovoid Leading Questions

Another related example is how the question is worded. An example would be: "Would you like a pay raise to increase productivity?". While it may be true that most people would, the wording makes it very unlikely that anyone would say no. This is a subtle point. Because most people would like a pay raise it is unlikely that they would say no. Therefore, some people are actually answering about the pay raise and it does not really matter if the productivity were to increase. The same results could occur if the question involved pay raise and lower productivity. This is because pay raise is a positive aspect of the question and creates a bias toward answering yes. A better wording would be to ask: "Please list the top 3 things that you think would increase productivity?". Now the respondents can answer how they truly feel without bias.


## How To Ovoid Leading Questions

Finally, there is one other factor that may lead or influence that way a respondent answers a question. It is important to avoid very emotional words. Emotional words could be either positive or negative. People are more likely to agree with emotionally positive words and less likely to agree with  emotionally negative words. These words could also potentially elicit emotional responses that in turn affect judgment and the way the question is answered.

- See the work by Jennifer Lerner to learn more about emotions and judgment. See the work by Joshua Greene to learn how presentation of scenarios can affect judgments and responses.


## How To Create Simple And Non-Complex Questions

It is also important to avoid complex questions that may not be very simple and clear. As we have discussed, if the respondent is spending time attempting to understand the question then there is less time and effort spent on simply answering how the respondent feels honestly. An example is: "Do you think having increased disposable income would yield an increase a positive valence of affect". What this question is asking is simple "Do you think having more income would increase happiness?". Using complicated words creates a question that may be difficult for many to understand and interpret.


## How To Create Simple And Non-Complex Questions

Another issue with keeping questions simple is to avoid negative wording. Negative wording here is dealing with negatives in the grammatical sense. This is not saying you cannot ask questions about negative topics. For example a question could be: "Do you think not increasing pay will lead to not increasing productivity?". This is a complicated way to ask the question and can cause confusion for the respondent. You could ask the question in a simpler way, such as: "Do you think increasing pay will lead to increasing productivity?" or "Do you think decreasing pay will lead to decreasing productivity?". There could be subtle differences in the interpretation of the two, but essentially they are asking the same concept, which is the belief in the relationship between pay and productivity. 


## How To Create Simple And Non-Complex Questions

One final point that is often confused with negatively worded questions can be seen in the questions that were just presented to reverse the negative wording of having the phrases "increasing pay" increasing productivity" decreasing pay" and "decreasing productivity". As mentioned, the two words are essentially asking the same thing. However, the difference in interpretation still exists. This is actually a good thing for survey design. 


## How To Create Simple And Non-Complex Questions

The question: "Do you think increasing pay will lead to increasing productivity?" is asking about something in a "positive" way semantically. The question: "Do you think decreasing pay will lead to decreasing productivity?" is asking the question in a "negative" way semantically. As previously stated, these questions are actually asking the same thing. Using both semantically "positive" and "negative" questions is very important in a survey. People sometimes tend to respond with agreement more often to questions that are semantically "positive". Therefore, having both semantically "positive" and "negative" questions in the survey helps to obtain more truthful responses.


## The Importance Of Presenting The Optimal Number Of Questions

The optimal number of questions to include in a survey is not always a simple decision. As we discussed in the last unit, respondents can experience fatigue if the survey is too long. This can lead to simply answering all of the questions in one way without thinking carefully about how to answer. 


## The Importance Of Presenting The Optimal Number Of Questions

The general principle is to use as few questions as necessary. However, there are cases where you need to include more questions and not fewer. One issue can be if the survey has questions that are all about one topic. It may seem that if this topic is what is being researched than that is sufficient. However, as we discussed researcher demand, the respondents may know exactly what you a trying to evaluate. This can lead to biasing and altering the answers because the purpose of the survey is to obvious. 


## The Importance Of Presenting The Optimal Number Of Questions

A solution is to embed other question among the questions that are important. This will help to avoid the situation where the respondents know what you may be trying to show with the data. While we did discuss the importance of not including questions that are not related to the particular research study, this is an example where it is acceptable and better to add unrelated questions.


## The Importance Of Presenting The Optimal Number Of Questions

Often it is important to include more than the minimum number of questions and also to ask about similar topics in multiple questions. Consider being asked something once. It is very possible that you provide an answer, but may not be completely certain of how you feel or think about the question. Because of this, asking multiple question about the same topic allows the researcher to get a better overall response of the true underlying feelings and thoughts about the respondents answer. 


## The Importance Of Presenting The Optimal Number Of Questions

There are also statistical and analytical considerations, which are a factor when determining the optimal number of questions. There must be a sufficient number of questions to be able to statistically analyze the data, enough variance to analyze the data, and also enough statistical power to have a chance of obtaining significant results. This is another example of why it is very important to develop an analysis plan before creating the survey or any type of research method. 


## Ask About Only One Thing At A Time

The final principle that was discussed generally in the last unit is to only ask about one thing at a time. A good survey question will never ask about two different things, concepts, etc. in one question. This can create much difficulty in answering the question.



## Ask About Only One Thing At A Time

Let us consider the pay and productivity example. It is possible that people are asked if an increase in pay makes them more productive and improves morale. This seems like a very reasonable question, but on closer examination causes problems. It is very likely that people are more productive and have higher morale with a pay raise. However, some people may view a pay raise as a contractual agreement to work harder and be more productive. It could even lead to lower morale because of factors like stress from the harder work. It is also possible that a pay raise increases morale due to simply appreciating the pay raise, but do not necessarily work any harder. The takeaway is that asking two questions at one time can cause conflict in how to answer and hurts the data.


## How Should Questions Be Ordered In A Survey

We discussed how to decide the optimal number of questions. Now we will discuss the order of questions. The order is very important and can affect the way people respond. One issue is that the respondents should trust the researcher. This will lead to more truthful responses. In an organization, there may be questions that deal with sensitive material, personal interactions, or personal opinions. If the respondents do not fully trust the researcher there is a chance that the respondents will be concerned about answering truthfully to protect themselves. Therefore, it is important not to begin a survey with sensitive or personal questions when possible.


## How Should Questions Be Ordered In A Survey

As previously mentioned, it is sometimes important that the respondents do not see exactly the purpose or hypothesis of the research or evaluation. This is the reason to sometimes embed unrelated questions so not to reveal the purpose or the hypothesis. 


## How Should Questions Be Ordered In A Survey

A final concern with the order is how the questions in the beginning of the survey could affect the responses in subsequent questions. For example, a question could ask about how someone feels generally about the quality of the organization. Let us assume that a person answered positively. If there are question later in the survey that ask about details of the organization there is a potential internal conflict in the respondent. For example, the question "How do you feel about management at the organization?" could present a conflict if the answer about the organization in general was positive it may be difficult for someone to respond negatively about management because this could contradict the previous answer about management. Therefore, it is important to consider the effect of questions on related subsequent questions.


## Types Of Survey Aswers

There are many ways that a respondent can answer questions. The type of answers often depends on the goals of the research, the type of analysis that will be conducted, and the type of information that is needed from the evaluation. This is similar to many themes that we have seen. One important thing to keep in mind is that surveys may use different types of answers in one survey when it is needed.


## Types Of Survey Aswers

One way to design survey questions is to have open-ended questions. This is when people can freely respond however they would like. This can be very useful. As with observational studies, there are many things that a researcher may not know. By allowing a free response a researcher can learn many in depth viewpoints and characteristics of the organization and its functioning. This provides potentially much data that can be very valuable and informative. 


## Types Of Survey Aswers

There are some disadvantages with open-ended questions. One is that the respondent may not actually answer questions with the information for which is being asked. The answer can stray from the topic. This would yield data that may not be useful for the evaluation. Sometimes restricting the scope of answer may be more productive. However, any restrictions must maintain objectivity and not limit responses in such a way that will bias answers to confirm a hypothesis.


## Types Of Survey Aswers

Open-ended questions have many similarities with observational studies. Open-ended questions must be interpreted by the researcher. As with observational studies, a systematic coding system must exist to be sure that the data is valid and reliable, and also objective. The only difference is that there are now direct questions. This should help to minimize some of the need for interpretation. However, open-ended questions are not as simple to statistically analyze. Therefore, it is very important, as with other methods, to have an analysis plan before creating the survey.


## Types Of Survey Aswers

Another class of answers that are used are involve very simple do you agree or disagree answers and yes or no answers. These can be very useful because the answers are very clear and need no interpretation. These are also much more easy to analyze and can be used with several statistical models, such as regression, ANOVA, and simple comparisons of means. One disadvantage is that there are often cases where a respondent is not precisely in a yes or no category. This can lead to lower quality data because either option is not exactly how the respondent feels.


## Types Of Survey Aswers

Because having only two choices can sometimes be too restrictive and not allow for the true response, a good way is to expand the options. Instead of asking do you agree or disagree, it could be better to provide a scale of options. These may range from 1-5 where 1 is completely disagree and 5 is completely agree. This is called a Likert Scale. Typically these scales are either 1-5 or 1-7. There are other ranges of scales. One important consideration is to use an odd numbered scale. This will provide a middle point where often the option is "neutral, or "neither agree nor disagree". The other options such as 2 and 4 on a 1-5 scale is often "somewhat disagree" for 2 and "somewhat agree" for 3. This provides a full range of options, while restricting the answers.  



## Types Of Survey Aswers

As mentioned, there are other ranges of scales. A researcher should be careful when deciding on the range. If there are too few options then again we encounter the situation of the respondent not being able to answer precisely truthful always. If we have too many options then the respondent may not know exactly how to respond due to too many options to consider. It is also important to label what each number on the scale means. As with keeping questions simple, by not labeling the meaning of each number there is more complexity and need for the respondent to interpret what the number means. 


## Types Of Survey Aswers

One final consideration with Likert Scales is that it is important to keep all of the ranges of the scales the same. First, it begins to confuse the respondent when scale ranges change. Second, it is difficult to compare the data from different ranges. However, depending on the type of question there may be a need to have different types of responses, but when using a scale it is best to remain with the same range throughout the survey.


## Interviews: Collecting Data In Person

Interviews are very closely related to surveys in research and evaluation. In general all of the principles from survey design apply to interviewing techniques. It is important to ask simple questions, not ask leading questions, consider the number of questions, and ask only one thing in each questions. The order of the questions and the types of responses are also just as important in interviews.


## Interviews: Collecting Data In Person

Interviews have some advantages. One advantage is question probes. As mentioned with survey questions, sometimes people misinterpret the questions or do not actually answer with the information in which the researcher is interested. Because the interviewer is face-to-face there is the opportunity to ask additional questions when this occurs. This is not meant to be a method to get the answer that the research wants, but rather get an answer that is appropriate for the question being asked.


## Interviews: Collecting Data In Person

Sometimes a person may be more comfortable answering directly to a person. However, the opposite can also be true. With surveys there is some level of anonymity. When being face-to-face there is less privacy. The researcher still must keep the data anonymous. 


## Interviews: Collecting Data In Person

Another challenge, as with observational studies, there is often a level of interpretation. Luckily with interviews they can be structured more like a survey to limit the interpretation. Another challenge is the demeanor of the interviewer. It is very important for the interviewer to appear neutral and not to have any facial expressions or reactions that may affect how a person responds. Interviews are interpersonal interactions and much care should be take to not let characteristics of the interviewer bias the responses. This why, as with observational studies, preparation, training, and practice is essential before beginning interviews. This also involves a well prepared systematic coding system.


## Overview Of Survey Design And Interviews

We have covered many details of how to create good questions for asking people directly, whether in a survey format or in an interview setting. We have moved to a closer interaction between the respondents in organizations and the researchers. This presents many potential opportunities, yet also presents new challenges. Surveys and interviews are methods that often can provide additional information.


## Looking Forward

- We will begin to discuss types of methods that are more experimental in nature

- We will begin with simple experimental designs and progress to more complex designs

- We will discuss the advantages and disadvantages of experimental methods in program evaluation










